development:
  cloud_name: <%= ENV['CLOUDINARY_NAME'] %>
  api_key:    <%= ENV['CLOUDINARY_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_file_support: false